os: Visual Studio 2015

platform:
  - x64
  - x86

environment:
  DUGITE_CACHE_DIR: '%USERPROFILE%\.dugite\'
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'
    - nodejs_version: '11'

cache:
  - '%USERPROFILE%\.dugite\'
  - '%USERPROFILE%\.npm\'

branches:
  only:
    - master
    - v2
    - /^greenkeeper/.*$/
    - /releases\/.*/

skip_tags: true

version: '{build}'

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm ci
  - npm run is-it-pretty

build_script:
  - npm run build

test_script:
  - set TEST=1
  - npm test
